routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//testing
Route::get('/backend2', function(){
	return view('layouts.backend2');
});
Route::get('/login2', function(){
	return view('auth.test_login');
});

//Backend
Auth::routes();
Route::get('admin-login', 'Auth\AdminLoginController@showLoginForm')->name('admin-login');
Route::post('admin-login', ['as'=>'admin-login','uses'=>'Auth\AdminLoginController@login']);
Route::get('admin-logout', 'Auth\AdminLoginController@logout')->name('admin.logout');

Route::prefix('backend')->middleware('auth:admin')->namespace('backend')->group(function(){
    Route::get('/', 'AdminController@dashboard')->name('backend');
    Route::resource('admins', 'AdminController');
    Route::resource('categories', 'CategoryController');
    Route::resource('songs', 'SongController');
    Route::post('songs/search', 'SongController@search')->name('songs.search');
});

Route::get('/test','backend\SongController@test');

//frontend
Route::get('/', 'HomeController@index')->name('home');

//Application
// Route::get('{any}', 'AppController@index')->where('any', '[\/\w\.-]*');

//facebook login
Route::post('/sociallogin/{provider}', 'api\RegisterController@SocialSignup');
Route::get('/app/auth/{provider}/callback', 'api\RegisterController@callBack')->where('provider', '.*');

app/Song.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
// use Kyawnaingtun\Tounicode\TounicodeTrait;

class Song extends Model
{
    // use TounicodeTrait;
    
    protected $fillable = [
        'uniquid','user_id', 'user_type', 'song_category_id',
        'title','composer','singer','key','style','youtube_id', 'description','content','chord',
        'public_status'
    ];

    // protected $convertable = ['title','composer','singer','key','style','mp3','description','content','chord'];

    public function song_category()
    {
        return $this->belongsTo('App\SongCategory');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function admin()
    {
        return $this->belongsTo('App\Admin', 'user_id');
    }

    public function song_views()
    {
        return $this->hasMany('App\SongView');
    }
}

app/SongView.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SongView extends Model
{
    protected $fillable = [
        'song_id',
    ];
}

app/Http/Controllers/Application/SongController.php
<?php

namespace App\Http\Controllers\Application;

use Illuminate\Http\Request;
use App\Http\Controllers\Application\BaseController;
use App\Http\Resources\SongListResourceCollection;
use App\Http\Resources\SongListResource;
use App\Http\Resources\SongDetailResource;
use App\Song;
use App\SongView;

class SongController extends BaseController
{
    public function songList()
    {
        return new SongListResourceCollection(Song::where('public_status', 0)
                                                    ->withCount('song_views')->orderBy('song_views_count','desc')
                                                    ->paginate(10));
    }

    public function songDetail(Request $request)
    {
        SongView::Create([
            'song_id' => $request->id,
        ]);
        $responseBody = new SongDetailResource(Song::find($request->id));
        return $this->successResponse($responseBody, 'Success retrieve song detail');
    }

    public function categorySongList(Request $request)
    {
        return new SongListResourceCollection(Song::where('public_status', 0)
                                            ->where('song_category_id', $request->songCategoryId)
                                            ->paginate(10));
    }

    public function searchSong(Request $request)
    {
        if($request->searchData != '')
        {
            return new SongListResourceCollection(Song::where('title','like', '%' .  $request['searchData'] . '%')
                                        ->orWhere('content','like', '%' .  $request['searchData'] . '%')
                                        ->orWhere('uniquid','like', '%' .  $request['searchData'] . '%')
                                        ->limit(30)
                                        ->get());
        }
        
    }

    public function topSongList()
    {
        $responseBody = [
            'topSongList' => SongListResource::collection(Song::where('public_status', 0)
                                                                    ->withCount('song_views')->orderBy('song_views_count','desc')
                                                                    ->limit(10)
                                                                    ->get()),
        ];

        return $this->successResponse($responseBody, 'Success retrieve Top Song list');
    }
}

app/Http/Controllers/api/SongController.php
<?php

namespace App\Http\Controllers\api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Resources\SongCollection;
use App\Http\Resources\Song as SongResource;    
use App\Song;
use App\Category;
use Auth;
use Validator;
use Carbon\Carbon;

class SongController extends Controller
{
    public function index()
    {
        return new SongCollection(Song::where('public_status', 0)->paginate(10));        
    }

    public function categoryList($id)
    {
        return new SongCollection(Song::where('song_category_id',$id)
                                        ->where('public_status', 0)
                                        ->paginate(10));
    }

    public function show($id)
    {
        //$song = Song::find($id);
        
        //return response()->json($song);
        return new SongResource(Song::find($id));
    }

    public function edit($id)
    {
        return new SongResource(Song::find($id));
    }

    public function search(Request $request)
    {
        return new SongCollection(Song::where('title','like', '%' .  $request['search_data'] . '%')
                                        ->orWhere('content','like', '%' .  $request['search_data'] . '%')
                                        ->orWhere('uniquid','like', '%' .  $request['search_data'] . '%')
                                        ->get());
    }

    public function mySong()
    {
        return new SongCollection(Song::where('user_id', Auth::user()->id)->where('user_type', 'user')->paginate(10));
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required|max:30',            
            'category' => 'required',
            'composer' => 'max:30',
            'singer' => 'max:30',
            'key' => 'max:3',
            'style' => 'max:15',
            'description' => 'max:2000',
            'lyric' => 'required|min:20',
        ]);

        if($validator->fails()){
            return response()->json(['success'=>'validation_error', 'errors' => $validator->errors()]);       
        }

        $song= Song::Create([
            'user_id' => Auth::user()->id,
            'user_type' => 'user',
            'title' => $request['title'],
            'song_category_id' => $request['category'],
            'composer' => $request['composer'],
            'singer' => $request['singer'],
            'key' => $request['key'],
            'style' => $request['style'],
            'youtube_id' => $request['youtube_id'],
            'chord' => $request['chord'],
            'description' => $request['description'],
            'content' => $request['lyric'],
            'public_status' => $request['public_status'],
        ]);

        //create uniquid for song
        $now = Carbon::now();
        $second = $now->second;
        $second_string = strval($second);
        $length = strlen($second_string);

        if($length == 1)
        {
            $second = '0'.$second;
        }

        $uniquid = $second.$song->id;

        $song->uniquid = $uniquid;
        $song->save();

        return response()->json(['success' => true]);
    }

    public function update(Request $request,$id)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required|max:30',            
            'category' => 'required',
            'composer' => 'max:30',
            'singer' => 'max:30',
            'key' => 'max:3',
            'style' => 'max:15',
            'description' => 'max:2000',
            'lyric' => 'required|min:20',
        ]);

        if($validator->fails()){
            return response()->json(['success'=>'validation_error', 'errors' => $validator->errors()]);       
        }

        $song = Song::find($id);

        $song->title = $request['title'];
        $song->song_category_id = $request['category'];
        $song->composer = $request['composer'];
        $song->singer = $request['singer'];
        $song->key = $request['key'];
        $song->style = $request['style'];
        $song->chord = $request['chord'];
        $song->youtube_id = $request['youtube_id'];
        $song->description = $request['description'];
        $song->content = $request['lyric'];
        $song->public_status = $request['public_status'];

        $song->save();

        return response()->json(['success' => true]);
    }

    public function checkUserSong($song_id)
    {
        $user = Auth::user();
        $song = Song::find($song_id);

        if($user->id == $song->user_id)
        {
            return response()->json(['check' => true]);
        }
        else{
            return response()->json(['check' => false]);
        }

    }

    public function delete($song_id)
    {
        $song = Song::find($song_id);
        $song->delete();

        return response()->json(['success'=> true]);
    }
}

app/Http/Controllers/backend/AdminController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Admin;
use Validator;
use Illuminate\Support\Facades\Hash;

class AdminController extends Controller
{
    public function dashboard()
    {
        return view('backend.welcome');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $admins = Admin::paginate(10);
        return view('backend.admins.index', compact('admins'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.admins.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255',
            'password' => 'required|string|min:8|same:confirm_password',            
            'confirm_password' => 'required|string|min:8',
        ]);

        if ($validator->fails()) {
            return redirect()->route('admins.create')
                        ->withErrors($validator)
                        ->withInput();
        }

        Admin::create([
            'name' => $request['name'],
            'email' => $request['email'],
            'password' => Hash::make($request['password']),
        ]);

        return redirect()->route('admins.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $admin = Admin::find($id);
        return view('backend.admins.show', compact('admin'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $admin = Admin::find($id);
        return view('backend.admins.edit', compact('admin'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $admin = Admin::find($id);
        $validator = Validator::make($request->all(), [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255',
        ]);

        if ($validator->fails()) {
            return redirect(route('admins.edit'), $admin->id)
                        ->withErrors($validator)
                        ->withInput();
        }

        if($request['password'] == null)
        {            
            
            $admin->name = $request['name'];
            $admin->email = $request['email'];
            $admin->update();

            return redirect()->route('admins.index');
        }
        else
        {
            $admin->name = $request['name'];
            $admin->email = $request['email'];
            $admin->password = Hash::make($request['password']);
            $admin->update();

            return redirect()->route('admins.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $admin = Admin::find($id);
        $admin->delete();

        return redirect()->back();
    }
}

app/Http/Controllers/backend/CategoryController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\SongCategory;
use Validator;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\File;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = SongCategory::orderBy('id','asc')->paginate(10);
        return view('backend.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make($request->all(), [
            'title' => 'required|max:255',
            'description' => 'required|max:255',
            'file' => 'required|image',
        ])->validate();

        if($request->hasFile('file'))
        {
                $file = $request->file('file');
                $filename = uniqid().'_'.$file->getClientOriginalName();
                Storage::disk('public')->putFileAs('/uploads/category/', $file, $filename);
        }

        SongCategory::Create([
            'title' => $request['title'],
            'description' => $request['description'],
            'file' => $filename,
        ]);

        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = SongCategory::find($id);
        return view('backend.categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = SongCategory::find($id);
        return view('backend.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Validator::make($request->all(), [
            'title' => 'required|max:255',
            'description' => 'required|max:255',
        ])->validate();       

        $category =  SongCategory::find($id);

        if($request->hasFile('file'))
        {
                $file = $request->file('file');
                $filename = uniqid().'_'.$file->getClientOriginalName();
                Storage::disk('public')->delete('/uploads/category/'. $category->file);
                Storage::disk('public')->putFileAs('/uploads/category/', $file, $filename);
                $category->file = $filename;
        }

        $category->title = $request['title'];
        $category->description = $request['description'];        
        $category->save();

        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = SongCategory::find($id);
        $songs = $category->songs;

        if($songs->count() == 0)
        {
            Storage::disk('public')->delete('/uploads/category/'. $category->file);
            $category->delete();
            return redirect(route('categories.index'));
        }
        else{
            return redirect()->back()->with('alert', 'Sorry,You can only delete when this category have no songs!');
        }


        
    }
}

resources/views/backend/songs/edit.blade.php
@extends('layouts.backend')
@section('title','Song|Edit')

@section('head_title','Song')

@section('breadcrumbs')
    <li class="m-nav__item">
        <a href="{{route('songs.index')}}" class="m-nav__link">
            <span class="m-nav__link-text">Song</span>
        </a>
    </li>
    <li class="m-nav__separator">-</li>
    <li class="m-nav__item">
        <a href="{{route('songs.edit', $song->id)}}" class="m-nav__link">
            <span class="m-nav__link-text">Edit</span>
        </a>
    </li>   
@endsection

@section('content')



<!--begin::Portlet-->
    <div class="m-portlet m-portlet--tab">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <span class="m-portlet__head-icon m--hide">
                        <i class="la la-gear"></i>
                    </span>
                    <h3 class="m-portlet__head-text">
                        Song Edit
                    </h3>
                </div>
            </div>
        </div>

        

        <!--begin::Form-->
        <form method="POST" action="{{route('songs.update', $song->id)}}" class="m-form m-form--fit m-form--label-align-right">
            @csrf
            @method('PUT')
            <div class="m-portlet__body">
                @if ($errors->any())
                    <div class="form-group m-form__group m--margin-top-10">   
                        <div class="alert alert-danger m-alert m-alert--default" role="alert">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                        </div>
                    </div>
                @endif
                <div class="form-group m-form__group">
                    <label>Title</label>
                    <input type="text" value="{{$song->title}}" name="title" class="form-control m-input m-input--air" placeholder="Enter title">
                </div>
                <div class="form-group m-form__group">
                    <label for="exampleSelect1">Select Category</label>
                    <select name="song_category_id" class="form-control m-input m-input--air">
                        @foreach ($categories as $category)
                                <option value="{{$category->id}}">{{$category->title}}</option>
                        @endforeach    
                    </select>
                </div>
                <div class="form-group m-form__group">
                    <label>Composer</label>
                    <input type="text" value="{{$song->composer}}" name="composer" class="form-control m-input m-input--air" placeholder="Enter composer">
                </div>
                <div class="form-group m-form__group">
                    <label>Singer</label>
                    <input type="text" name="singer" value="{{$song->singer}}" class="form-control m-input m-input--air" placeholder="Enter singer">
                </div>
                <div class="form-group m-form__group">
                    <label>Key</label>
                    <input type="text" name="key" value="{{$song->key}}" class="form-control m-input m-input--air" placeholder="Enter key">
                </div>
                <div class="form-group m-form__group">
                    <label>Style</label>
                    <input type="text" name="style" value="{{$song->style}}" class="form-control m-input m-input--air" placeholder="Enter style">
                </div>
                <div class="form-group m-form__group">
                    <label>Youtube Id</label>
                    <input type="text" name="youtube_id" value="{{$song->youtube_id}}" class="form-control m-input m-input--air" placeholder="Enter Youtube Id">
                </div>
                <div class="form-group m-form__group">
                    <label for="exampleTextarea">Description</label>
                    <textarea name="description" class="form-control m-input" rows="3">{{$song->description}}</textarea>
                </div>
                <div class="form-group m-form__group">
                    <label>Content</label>
                    <div>
                        <textarea name="content" id="content_editor" class="form-control">{{$song->content}}</textarea>
                    </div>
                </div>
                <div class="form-group m-form__group">
                    <label>Chord</label>
                    <div>
                        <textarea name="chord" id="chord_editor" class="form-control">{{$song->chord}}</textarea>
                    </div>
                </div>
            </div>
            <div class="m-portlet__foot m-portlet__foot--fit">
                <div class="m-form__actions">
                    <button type="submit" class="btn btn-danger">Update</button>
                    <a href="{{route('songs.index')}}" class="btn btn-secondary">Cancel</a>
                </div>
            </div>
        </form>

        <!--end::Form-->
    </div>

    <!--end::Portlet-->
@endsection

@section('head')
    <styLe>
        p {
            /* margin: 5px; */
            line-height: 5;
        }
    </style>
@endsection

@section('script')
<script src="{{asset('/vendor/unisharp/laravel-ckeditor/ckeditor.js')}}"></script>
    <script>
        CKEDITOR.replace( 'content_editor' );
        CKEDITOR.replace( 'chord_editor' );
    </script>
@endsection

resources/views/backend/songs/index.blade.php
@extends('layouts.backend')
@section('title','Karani | Songs')

@section('head_title','Song')

@section('breadcrumbs')
    <li class="m-nav__item">
        <a href="{{route('songs.index')}}" class="m-nav__link">
            <span class="m-nav__link-text">Song</span>
        </a>
    </li>
    <li class="m-nav__separator">-</li>
    <li class="m-nav__item">
        <a href="{{route('songs.index')}}" class="m-nav__link">
            <span class="m-nav__link-text">Table</span>
        </a>
    </li>   
@endsection

@section('content')

<div class="box">

        {{-- <div class="m-alert m-alert--icon m-alert--air m-alert--square alert alert-dismissible m--margin-bottom-30" role="alert">
            <div class="m-alert__icon">
                <i class="flaticon-exclamation m--font-brand"></i>
            </div>
            <div class="m-alert__text">
                The Metronic Datatable component supports local or remote data source. For the local data you can pass javascript array as data source. In this example the grid fetches its data from a javascript array data source. It also defines the schema
                model of the data source. In addition to the visualization, the Datatable provides built-in support for operations over data such as sorting, filtering and paging performed in user browser(frontend).
            </div>
        </div> --}}
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Category Table<small>Control all of category accounts</small>
                        </h3>
                    </div>
                </div>
            </div>
            <div class="m-portlet__body">                
                    <!--begin: Search Form -->
                    <form method="POST" action="{{route('songs.search')}}">
                    @csrf
                        <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                            <div class="row align-items-center">
                                <div class="col-xl-8 order-2 order-xl-1">
                                    <div class="form-group m-form__group row align-items-center">
                                        <div class="col-md-4">
                                            <div class="m-input-icon m-input-icon--left">
                                                <input type="text" name="search" class="form-control m-input m-input--solid" placeholder="Search..." id="generalSearch" required="true">
                                                <span class="m-input-icon__icon m-input-icon__icon--left">
                                                    <span><i class="la la-search"></i></span>
                                                </span>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <button type="submit" class="btn btn-danger m-btn m-btn--custom m-btn--icon m-btn--air">
                                                <span>
                                                    <i class="la la-search"></i>
                                                    <span>Search</span>
                                                </span>
                                            </button>
                                            <a href="{{route('songs.index')}}" class="btn btn-danger m-btn m-btn--custom m-btn--icon m-btn--air">
                                                    <span>All</span>                        
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                                    <a href="{{route('songs.create')}}" class="btn btn-danger m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
                                        <span>
                                            <i class="la la-plus"></i>
                                            <span>Create</span>
                                        </span>
                                    </a>
                                    <div class="m-separator m-separator--dashed d-xl-none"></div>
                                </div>
                            </div>
                        </div>
                    </form>

                <!--end: Search Form -->

                <!--begin: Datatable -->
                <div class="table-responsive">
                    <table class="table table-bordered table-hover" id="html_table" width="100%">
                        <thead>
                            <tr>
                                <th title="Field #1" data-field="No">No</th>
                                <th title="Field #1" data-field="No">Code Id</th>
                                <th title="Field #2" data-field="Title">Title</th>
                                <th title="Field #2" data-field="Category">Category</th>
                                <th title="Field #3" data-field="Description">Description</th>
                                <th title="Field #4" data-field="Action">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($songs as $key=>$song)
                                <tr>
                                    <td>{{ $key+ $songs->firstItem() }}</td>
                                    <td>{{$song->uniquid}}</td>
                                    <td>{{$song->title}}</td>
                                    <td>{{$song->song_category->title}}</td>
                                    <td>{{$song->description}}</td>
                                    <td>
                                        <a class="btn btn-outline-success m-btn m-btn--icon m-btn--icon-only m-btn--outline-2x m-btn--pill m-btn--air" href="{{route('songs.show', $song->id)}}">
                                            <i class="fa fa-eye"></i>
                                        </a>

                                        <a class="btn btn-outline-info m-btn m-btn--icon m-btn--icon-only m-btn--outline-2x m-btn--pill m-btn--air" href="{{route('songs.edit', $song->id)}}"><i class="fa fa-edit"></i></a>

                                        <form action="{{route('songs.destroy', $song->id)}}" method="POST" style="display:inline;">
                                            @csrf
                                            @method('DELETE')                                            
                                            <button type="submit" class="btn btn-outline-danger m-btn m-btn--icon m-btn--icon-only m-btn--outline-2x m-btn--pill m-btn--air" onclick="return confirm('Are you sure to delete it?')"><i class="fa fa-trash"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>                                     
                    </table>         
                    {{ $songs->links() }}              
                </div>

                <!--end: Datatable -->
            </div>
            
        </div>
</div>

@endsection

@section('head')
    <style>
        .col-width{
            text-align: center;
            width: 50px;
        }

        th{
            text-align: center;
        }

        td{
            text-align: center;
        }
    </style>
@endsection