routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//testing
Route::get('/backend2', function(){
	return view('layouts.backend2');
});
Route::get('/login2', function(){
	return view('auth.test_login');
});

//Backend
Auth::routes();
Route::get('admin-login', 'Auth\AdminLoginController@showLoginForm')->name('admin-login');
Route::post('admin-login', ['as'=>'admin-login','uses'=>'Auth\AdminLoginController@login']);
Route::get('admin-logout', 'Auth\AdminLoginController@logout')->name('admin.logout');

Route::prefix('backend')->middleware('auth:admin')->namespace('backend')->group(function(){
    Route::get('/', 'AdminController@dashboard')->name('backend');
    Route::resource('admins', 'AdminController');
    Route::resource('categories', 'CategoryController');
    Route::resource('songs', 'SongController');
    Route::post('songs/search', 'SongController@search')->name('songs.search');
});

Route::get('/test','backend\SongController@test');

//frontend
Route::get('/', 'HomeController@index')->name('home');

//Application
// Route::get('{any}', 'AppController@index')->where('any', '[\/\w\.-]*');

//facebook login
Route::post('/sociallogin/{provider}', 'api\RegisterController@SocialSignup');
Route::get('/app/auth/{provider}/callback', 'api\RegisterController@callBack')->where('provider', '.*');

app/Http/Controllers/backend/AdminController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Admin;
use Validator;
use Illuminate\Support\Facades\Hash;

class AdminController extends Controller
{
    public function dashboard()
    {
        return view('backend.welcome');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $admins = Admin::paginate(10);
        return view('backend.admins.index', compact('admins'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.admins.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255',
            'password' => 'required|string|min:8|same:confirm_password',            
            'confirm_password' => 'required|string|min:8',
        ]);

        if ($validator->fails()) {
            return redirect()->route('admins.create')
                        ->withErrors($validator)
                        ->withInput();
        }

        Admin::create([
            'name' => $request['name'],
            'email' => $request['email'],
            'password' => Hash::make($request['password']),
        ]);

        return redirect()->route('admins.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $admin = Admin::find($id);
        return view('backend.admins.show', compact('admin'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $admin = Admin::find($id);
        return view('backend.admins.edit', compact('admin'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $admin = Admin::find($id);
        $validator = Validator::make($request->all(), [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255',
        ]);

        if ($validator->fails()) {
            return redirect(route('admins.edit'), $admin->id)
                        ->withErrors($validator)
                        ->withInput();
        }

        if($request['password'] == null)
        {            
            
            $admin->name = $request['name'];
            $admin->email = $request['email'];
            $admin->update();

            return redirect()->route('admins.index');
        }
        else
        {
            $admin->name = $request['name'];
            $admin->email = $request['email'];
            $admin->password = Hash::make($request['password']);
            $admin->update();

            return redirect()->route('admins.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $admin = Admin::find($id);
        $admin->delete();

        return redirect()->back();
    }
}

app/Http/Controllers/backend/CategoryController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\SongCategory;
use Validator;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\File;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = SongCategory::orderBy('id','asc')->paginate(10);
        return view('backend.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make($request->all(), [
            'title' => 'required|max:255',
            'description' => 'required|max:255',
            'file' => 'required|image',
        ])->validate();

        if($request->hasFile('file'))
        {
                $file = $request->file('file');
                $filename = uniqid().'_'.$file->getClientOriginalName();
                Storage::disk('public')->putFileAs('/uploads/category/', $file, $filename);
        }

        SongCategory::Create([
            'title' => $request['title'],
            'description' => $request['description'],
            'file' => $filename,
        ]);

        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = SongCategory::find($id);
        return view('backend.categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = SongCategory::find($id);
        return view('backend.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Validator::make($request->all(), [
            'title' => 'required|max:255',
            'description' => 'required|max:255',
        ])->validate();       

        $category =  SongCategory::find($id);

        if($request->hasFile('file'))
        {
                $file = $request->file('file');
                $filename = uniqid().'_'.$file->getClientOriginalName();
                Storage::disk('public')->delete('/uploads/category/'. $category->file);
                Storage::disk('public')->putFileAs('/uploads/category/', $file, $filename);
                $category->file = $filename;
        }

        $category->title = $request['title'];
        $category->description = $request['description'];        
        $category->save();

        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = SongCategory::find($id);
        $songs = $category->songs;

        if($songs->count() == 0)
        {
            Storage::disk('public')->delete('/uploads/category/'. $category->file);
            $category->delete();
            return redirect(route('categories.index'));
        }
        else{
            return redirect()->back()->with('alert', 'Sorry,You can only delete when this category have no songs!');
        }


        
    }
}

app/Http/Controllers/backend/SongController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Song;
use App\SongCategory;
use Validator;
use Carbon\Carbon;
use Auth;

class SongController extends Controller
{
    public function test()
    {
        $now = Carbon::now();
        $second = $now->second;
        $second_string = strval($second);
        $length = strlen($second_string);

        if($length == 1)
        {
            $second = '0'.$second;
        }

        return 'second=> '.$second.'<br>'.'count '.$length;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $songs = Song::paginate(10);
        $song = Song::find(3);

        return view('backend.songs.index', compact('songs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = SongCategory::all();
        return view('backend.songs.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make($request->all(), [
            'title' => 'required|max:255',
            'content' => 'required',
        ])->validate();

        $song = Song::Create([
            'user_id' => Auth::user()->id,
            'user_type' => 'admin',
            'title' => $request['title'],
            'song_category_id' => $request['song_category_id'],
            'composer' => $request['composer'],
            'singer' => $request['singer'],
            'key' => $request['key'],
            'style' => $request['style'],
            'youtube_id' => $request['youtube_id'],
            'chord' => $request['chord'],
            'description' => $request['description'],
            'content' => $request['content'],
        ]);


        //create uniquid for song
        $now = Carbon::now();
        $second = $now->second;
        $second_string = strval($second);
        $length = strlen($second_string);

        if($length == 1)
        {
            $second = '0'.$second;
        }

        $uniquid = $second.$song->id;

        $song->uniquid = $uniquid;
        $song->save();

        return redirect(route('songs.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {        
        $song = Song::find($id);
        return view('backend.songs.show', compact('song'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = SongCategory::all();
        $song = Song::find($id);
        return view('backend.songs.edit', compact('song','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $song = Song::find($id);
        Validator::make($request->all(), [
            'title' => 'required|max:255',
            'content' => 'required',
        ])->validate();

            $song->title = $request['title'];
            $song->song_category_id = $request['song_category_id'];
            $song->composer = $request['composer'];
            $song->singer = $request['singer'];
            $song->key = $request['key'];
            $song->style = $request['style'];
            $song->youtube_id = $request['youtube_id'];
            $song->chord = $request['chord'];
            $song->description = $request['description'];
            $song->content = $request['content'];

            $song->save();

        return redirect(route('songs.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $song = Song::find($id);
        $song->delete();

        return redirect(route('songs.index'));
    }

    public function search(Request $request)
    {
        $search = $request['search'];

        $songs = Song::where('title','like','%'.$search.'%')
                        ->orWhere('content','like','%'.$search.'%')
                        ->orWhere('uniquid','like','%'.$search.'%')
                        ->orwhereHas('song_category', function($query) use ($search){
                            $query->where('title', 'like', '%'.$search.'%');
                        })
                        ->paginate(10);

        return view('backend.songs.index', compact('songs'));
    }
}

resources/views/backend/admins/create.blade.php
@extends('layouts.backend')
@section('title','Admins|Create')

@section('head_title','Administrator')

@section('breadcrumbs')
    <li class="m-nav__item">
        <a href="{{route('admins.index')}}" class="m-nav__link">
            <span class="m-nav__link-text">Admin</span>
        </a>
    </li>
    <li class="m-nav__separator">-</li>
    <li class="m-nav__item">
        <a href="{{route('admins.index')}}" class="m-nav__link">
            <span class="m-nav__link-text">Create</span>
        </a>
    </li>   
@endsection


@section('content')



<!--begin::Portlet-->
    <div class="m-portlet m-portlet--tab">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <span class="m-portlet__head-icon m--hide">
                        <i class="la la-gear"></i>
                    </span>
                    <h3 class="m-portlet__head-text">
                        Admin Create
                    </h3>
                </div>
            </div>
        </div>

        

        <!--begin::Form-->
        <form method="POST" action="{{route('admins.store')}}" class="m-form m-form--fit m-form--label-align-right">
            @csrf
            <div class="m-portlet__body">
                @if ($errors->any())
                    <div class="form-group m-form__group m--margin-top-10">   
                        <div class="alert alert-danger m-alert m-alert--default" role="alert">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                        </div>
                    </div>
                @endif
                <div class="form-group m-form__group">
                    <label>Name</label>
                    <input type="text" name="name" class="form-control m-input m-input--air" placeholder="Enter name">
                </div>
                <div class="form-group m-form__group">
                    <label>Email</label>
                    <input type="email" name="email" class="form-control m-input m-input--air" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                    <span class="m-form__help">We'll never share your email with anyone else.</span>
                </div>
                <div class="form-group m-form__group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" name="password" class="form-control m-input m-input--air" id="exampleInputPassword1" placeholder="Password">
                </div>
                <div class="form-group m-form__group">
                    <label for="exampleInputPassword1">Confirm Password</label>
                    <input type="password" name="confirm_password" class="form-control m-input m-input--air" id="exampleInputPassword1" placeholder="Confirm Password">
                </div>
            </div>
            <div class="m-portlet__foot m-portlet__foot--fit">
                <div class="m-form__actions">
                    <button type="submit" class="btn btn-danger">Create</button>
                    <a href="{{route('admins.index')}}" class="btn btn-secondary">Cancel</a>
                </div>
            </div>
        </form>

        <!--end::Form-->
    </div>

    <!--end::Portlet-->

@endsection

resources/views/backend/admins/edit.blade.php
@extends('layouts.backend')
@section('title','Categories|Create')

@section('head_title','Administrator')

@section('breadcrumbs')
    <li class="m-nav__item">
        <a href="{{route('admins.index')}}" class="m-nav__link">
            <span class="m-nav__link-text">Admin</span>
        </a>
    </li>
    <li class="m-nav__separator">-</li>
    <li class="m-nav__item">
        <a href="{{route('admins.edit', $admin->id)}}" class="m-nav__link">
            <span class="m-nav__link-text">Edit</span>
        </a>
    </li>   
@endsection

@section('content')



<!--begin::Portlet-->
    <div class="m-portlet m-portlet--tab">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <span class="m-portlet__head-icon m--hide">
                        <i class="la la-gear"></i>
                    </span>
                    <h3 class="m-portlet__head-text">
                        Admin Edit
                    </h3>
                </div>
            </div>
        </div>

        

        <!--begin::Form-->
        <form method="POST" action="{{route('admins.update', $admin->id)}}" class="m-form m-form--fit m-form--label-align-right">
            @csrf
            @method('PUT')
            <div class="m-portlet__body">
                @if ($errors->any())
                    <div class="form-group m-form__group m--margin-top-10">   
                        <div class="alert alert-danger m-alert m-alert--default" role="alert">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                        </div>
                    </div>
                @endif
                <div class="form-group m-form__group">
                    <label>Name</label>
                    <input type="text" name="name" value="{{$admin->name}}" class="form-control m-input m-input--air" placeholder="Enter name">
                </div>
                <div class="form-group m-form__group">
                    <label>Email</label>
                    <input type="email" name="email" value="{{$admin->email}}" class="form-control m-input m-input--air" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                    <span class="m-form__help">We'll never share your email with anyone else.</span>
                </div>
                <div class="form-group m-form__group">
                    <label for="exampleInputPassword1">Change Password</label>
                    <input type="password" name="password" class="form-control m-input m-input--air" id="exampleInputPassword1" placeholder="Password">
                </div>
            </div>
            <div class="m-portlet__foot m-portlet__foot--fit">
                <div class="m-form__actions">
                    <button type="submit" class="btn btn-danger">Update</button>
                    <a href="{{route('admins.index')}}" class="btn btn-secondary">Cancel</a>
                </div>
            </div>
        </form>

        <!--end::Form-->
    </div>

    <!--end::Portlet-->




@endsection

resources/views/backend/admins/index.blade.php
@extends('layouts.backend')
@section('title','Karani | Admins')

@section('head_title','Administrator')

@section('breadcrumbs')
    <li class="m-nav__item">
        <a href="{{route('admins.index')}}" class="m-nav__link">
            <span class="m-nav__link-text">Admin</span>
        </a>
    </li>
    <li class="m-nav__separator">-</li>
    <li class="m-nav__item">
        <a href="{{route('admins.index')}}" class="m-nav__link">
            <span class="m-nav__link-text">Table</span>
        </a>
    </li>   
@endsection

@section('content')

<div class="box">

        {{-- <div class="m-alert m-alert--icon m-alert--air m-alert--square alert alert-dismissible m--margin-bottom-30" role="alert">
            <div class="m-alert__icon">
                <i class="flaticon-exclamation m--font-brand"></i>
            </div>
            <div class="m-alert__text">
                The Metronic Datatable component supports local or remote data source. For the local data you can pass javascript array as data source. In this example the grid fetches its data from a javascript array data source. It also defines the schema
                model of the data source. In addition to the visualization, the Datatable provides built-in support for operations over data such as sorting, filtering and paging performed in user browser(frontend).
            </div>
        </div> --}}
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Admin Table<small>Control all of admin accounts</small>
                        </h3>
                    </div>
                </div>
            </div>
            <div class="m-portlet__body">

                <!--begin: Search Form -->
                <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                    <div class="row align-items-center">
                        <div class="col-xl-8 order-2 order-xl-1">
                            <div class="form-group m-form__group row align-items-center">
                                <div class="col-md-4">
                                    <div class="m-input-icon m-input-icon--left">
                                        <input type="text" class="form-control m-input m-input--solid" placeholder="Search..." id="generalSearch">
                                        <span class="m-input-icon__icon m-input-icon__icon--left">
                                            <span><i class="la la-search"></i></span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                            <a href="{{route('admins.create')}}" class="btn btn-danger m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
                                <span>
                                    <i class="la la-plus"></i>
                                    <span>Create</span>
                                </span>
                            </a>
                            <div class="m-separator m-separator--dashed d-xl-none"></div>
                        </div>
                    </div>
                </div>

                <!--end: Search Form -->

                <!--begin: Datatable -->
                <div class="table-responsive">
                    <table class="table table-bordered table-hover" id="html_table" width="100%">
                        <thead>
                            <tr>
                                <th title="Field #1" data-field="No">No</th>
                                <th title="Field #2" data-field="Name">Name</th>
                                <th title="Field #3" data-field="Email">Email</th>
                                <th title="Field #4" data-field="Action">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($admins as $key=>$admin)
                                <tr>
                                    <td>{{ $key+ $admins->firstItem() }}</td>
                                    <td>{{$admin->name}}</td>
                                    <td>{{$admin->email}}</td>
                                    <td>
                                        <a class="btn btn-outline-success m-btn m-btn--icon m-btn--icon-only m-btn--outline-2x m-btn--pill m-btn--air" href="{{route('admins.show', $admin->id)}}">
                                            <i class="fa fa-eye"></i>
                                        </a>

                                        <a class="btn btn-outline-info m-btn m-btn--icon m-btn--icon-only m-btn--outline-2x m-btn--pill m-btn--air" href="{{route('admins.edit', $admin->id)}}"><i class="fa fa-edit"></i></a>

                                        <form action="{{route('admins.destroy', $admin->id)}}" method="POST" style="display:inline;">
                                            @csrf
                                            @method('DELETE')                                            
                                            <button type="submit" class="btn btn-outline-danger m-btn m-btn--icon m-btn--icon-only m-btn--outline-2x m-btn--pill m-btn--air" onclick="return confirm('Are you sure to delete it?')"><i class="fa fa-trash"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>                                     
                    </table>         
                    {{ $admins->links() }}              
                </div>

                <!--end: Datatable -->
            </div>
            
        </div>
</div>
@endsection

@section('head')
    <style>
        .col-width{
            text-align: center;
            width: 50px;
        }

        th{
            text-align: center;
        }

        td{
            text-align: center;
        }
    </style>
@endsection

resources/views/backend/admins/show.blade.php
@extends('layouts.backend')
@section('title','Category|View')

@section('head_title','Administrator')

@section('breadcrumbs')
    <li class="m-nav__item">
        <a href="{{route('admins.index')}}" class="m-nav__link">
            <span class="m-nav__link-text">Admin</span>
        </a>
    </li>
    <li class="m-nav__separator">-</li>
    <li class="m-nav__item">
        <a href="{{route('admins.show', $admin->id)}}" class="m-nav__link">
            <span class="m-nav__link-text">Show</span>
        </a>
    </li>   
@endsection

@section('content')

<div class="container col-md-8">
    <div class="card">
        <div class="container">
            <div class="card-title text-center mt-4 h3">Admin Detail</div>
            <div class="card-body">
                <table class="table table-bordered">
                    <tr>
                        <th> Title </th>
                        <td> {{$admin->name}} </td>
                    </tr>
                    <tr>
                        <th> Description </th>
                        <td> {{$admin->email}} </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection